SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((B.PRICE * S.SALES)) TOTAL_SALES
FROM BOOK B INNER JOIN AUTHOR A 
ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
