SELECT ANIMAL_ID, NAME
FROM ( 
       SELECT I.ANIMAL_ID, I.NAME, O.DATETIME-I.DATETIME AS C
       FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
       WHERE O.DATETIME IS NOT NULL
       ORDER BY C DESC
     )
WHERE ROWNUM <= 2