SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES  
FROM (
        SELECT  FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANK_NUM FROM REST_INFO
    ) T
WHERE T.RANK_NUM = 1
ORDER BY FOOD_TYPE DESC