SELECT U.USER_ID, U.NICKNAME, 
CONCAT(CONCAT(CONCAT(CONCAT(CITY,' '),STREET_ADDRESS1),' '),STREET_ADDRESS2) AS "전체주소",
REGEXP_REPLACE(TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS "전화번호"
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME,
CONCAT(CONCAT(CONCAT(CONCAT(CITY,' '),STREET_ADDRESS1),' '),STREET_ADDRESS2),
REGEXP_REPLACE(TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3')
HAVING COUNT(B.BOARD_ID) >= 3
ORDER BY U.USER_ID DESC