SELECT TO_CHAR(O.SALES_DATE,'YYYY') YEAR, TO_NUMBER(TO_CHAR(O.SALES_DATE,'MM')) MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO U INNER JOIN ONLINE_SALE O ON U.USER_ID = O.USER_ID
GROUP BY TO_CHAR(O.SALES_DATE,'YYYY'), TO_CHAR(O.SALES_DATE,'MM'), U.GENDER HAVING U.GENDER IS NOT NULL 
ORDER BY YEAR ASC, MONTH ASC, U.GENDER ASC