SELECT CH.HISTORY_ID
,CASE WHEN CH.END_DATE-CH.START_DATE+1 >= REGEXP_REPLACE(DP.DURATION_TYPE,'[^0-9]')     
    THEN ROUND(CR.DAILY_FEE*(CH.END_DATE-CH.START_DATE+1)*0.01*(100-REGEXP_REPLACE(DP.DISCOUNT_RATE,'[^0-9]')),1)
    ELSE CR.DAILY_FEE*(CH.END_DATE-CH.START_DATE+1) 
    END FEE
FROM CAR_RENTAL_COMPANY_CAR CR 
INNER JOIN 
CAR_RENTAL_COMPANY_RENTAL_HISTORY CH 
ON CR.CAR_ID = CH.CAR_ID 
INNER JOIN 
CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON CR.CAR_TYPE = DP.CAR_TYPE
WHERE DP.DURATION_TYPE LIKE 
    case when (CH.END_DATE-CH.START_DATE+1) BETWEEN 7 and 29 then '7일%'
         when (CH.END_DATE-CH.START_DATE+1) BETWEEN 30 and 89 then '30일%'
         when (CH.END_DATE-CH.START_DATE+1) >= 90 then '90일%'
         else '7일%' end
AND DP.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC