-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P 
INNER JOIN 
APPOINTMENT A 
ON P.PT_NO = A.PT_NO 
INNER JOIN
DOCTOR D 
ON D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD IN ('CS') 
AND A.APNT_CNCL_YMD IS NULL
AND TO_CHAR(A.APNT_YMD,'YYYYMMDD') = '20220413'
ORDER BY A.APNT_YMD ASC