SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE,'YYYY-MM-DD')
FROM MEMBER_PROFILE M INNER JOIN REST_REVIEW R 
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    -- WHERE ROWNUM=1
    GROUP BY MEMBER_ID 
    HAVING COUNT(REVIEW_ID) = (
        SELECT MAX(COUNT(REVIEW_ID)) FROM REST_REVIEW GROUP BY MEMBER_ID
    )
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC