-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE IN ('세단') AND TO_CHAR(H.START_DATE,'MM') IN ('10')
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC
