SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, CASE 
    WHEN STATUS IN ('SALE') THEN '판매중' 
    WHEN STATUS IN ('RESERVED') THEN '예약중' 
    WHEN STATUS IN ('DONE') THEN '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE TO_CHAR(CREATED_DATE,'YYYY-MM-DD') IN ('2022-10-05')
ORDER BY BOARD_ID DESC