SELECT CONCAT(CONCAT(CONCAT('/home/grep/src/',BOARD_ID),'/'),CONCAT(FILE_ID,CONCAT(FILE_NAME,FILE_EXT))) FILE_PATH
FROM (
    SELECT F.FILE_ID, 
            F.FILE_EXT, 
            F.FILE_NAME,B.BOARD_ID, 
            B.VIEWS,
            RANK() OVER(ORDER BY B.VIEWS DESC) RANK
    FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_FILE F 
    ON B.BOARD_ID = F.BOARD_ID
    ORDER BY B.VIEWS DESC
)
WHERE RANK = 1
ORDER BY FILE_ID DESC