SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) RANK, PRODUCT_NAME
    FROM FOOD_PRODUCT
)
WHERE CATEGORY IN ('과자','국','김치','식용유') AND RANK = 1
ORDER BY PRICE DESC
